### ISSUE TITLE
переход по страницам

### ISSUE THREAD

**Issue by Aristockij** [andrey-mitko/GSAP-Scroll-Fun#1]
если сделать другую страницу и переходить по ссылкам с помощью Link, то вылетает ошибка TypeError: Cannot read properties of undefined (reading 'match')

я так понимаю что в этот момент локомотив еще не успевает посчитать высоту, и вылетает эта ошибка.

**Comment by andrey-mitko** [comment]
Привет, я добавил `Link` на `div#nav` в `src/pages/index.tsx` и он без проблем открывает новую страницу. Пример новой страницы есть в `src/pages/greenBox.tsx` 🙌🏻

**Comment by Aristockij** [comment]
нет, точно такая же ошибка(
